---
asterisk_version: "22.5.2"

asterisk_src_base: "/usr/local/src"
asterisk_build_base: "/usr/src"

asterisk_download_base_url: "https://downloads.asterisk.org/pub/telephony/asterisk/old-releases"
asterisk_tarball_url: "{{ asterisk_download_base_url }}/asterisk-{{ asterisk_version }}.tar.gz"
asterisk_tarball_path: "{{ asterisk_build_base }}/asterisk-{{ asterisk_version }}.tar.gz"
asterisk_source_dir: "{{ asterisk_build_base }}/asterisk-{{ asterisk_version }}"

libpri_tarball_url: "https://downloads.asterisk.org/pub/telephony/libpri/libpri-1-current.tar.gz"
libpri_tarball_path: "{{ asterisk_build_base }}/libpri-1-current.tar.gz"

dahdi_linux_repo: "https://github.com/asterisk/dahdi-linux"
dahdi_linux_dir: "{{ asterisk_src_base }}/dahdi-linux"

dahdi_tools_repo: "https://github.com/asterisk/dahdi-tools"
dahdi_tools_dir: "{{ asterisk_src_base }}/dahdi-tools"

dahdi_linux_version: "master"
dahdi_tools_version: "master"

asterisk_user: "asterisk"
asterisk_group: "asterisk"

asterisk_make_jobs: 4

asterisk_use_saved_menuselect: true
asterisk_menuselect_makeopts_file: "menuselect.makeopts"

# chan_sip support for Asterisk 20+
# Used only for lab compatibility with legacy SIP tasks.
asterisk_enable_chan_sip: true
asterisk_force_rebuild: false
asterisk_chan_sip_reinclude_url: "https://raw.githubusercontent.com/InterLinked1/chan_sip/master/chan_sip_reinclude.sh"
asterisk_chan_sip_reinclude_script: "{{ asterisk_source_dir }}/chan_sip_reinclude.sh"

asterisk_chan_sip_create_minimal_sip_conf: true

# chan_sip base config
asterisk_enable_chan_sip: true
asterisk_chan_sip_bindaddr: "0.0.0.0"
asterisk_chan_sip_bindport: 5160

# PJSIP base config
asterisk_enable_pjsip: true
asterisk_pjsip_transport_name: "transport-udp"
asterisk_pjsip_bindaddr: "0.0.0.0"
asterisk_pjsip_bindport: 5060

